server:
  port: 8001

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      path: /h2
      enabled: true

logging:
  config: classpath:logback-spring-local.xml